# Generated by Django 6.0 on 2025-12-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test01',
            fields=[
                ('project_id01', models.CharField(max_length=50, verbose_name='项目编号')),
                ('equipment_id01', models.CharField(max_length=50, verbose_name='设备编号')),
                ('pk', models.CompositePrimaryKey('project_id01', 'equipment_id01', blank=True, editable=False, primary_key=True, serialize=False)),
                ('equipment_name01', models.CharField(max_length=100, verbose_name='设备名称')),
                ('equipment_quantity01', models.IntegerField(verbose_name='设备数量')),
            ],
            options={
                'verbose_name': '测试',
                'verbose_name_plural': '测试',
            },
        ),
    ]
