# Generated by Django 5.2.1 on 2025-06-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Equipment_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=50, verbose_name='项目编号')),
                ('equipment_id', models.CharField(max_length=50, verbose_name='设备编号')),
                ('equipment_name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('equipment_quantity', models.IntegerField(verbose_name='设备数量')),
            ],
            options={
                'verbose_name': '项目设备信息',
                'verbose_name_plural': '项目设备信息',
                'unique_together': {('project_id', 'equipment_id')},
            },
        ),
    ]
