# Generated by Django 6.0 on 2025-12-23 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_test01'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test01',
        ),
    ]
