# Generated by Django 6.0 on 2025-12-23 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_delete_test01'),
    ]

    operations = [
        # 空操作，跳过有问题的迁移
    ]
