# Generated by Django 6.0 on 2025-12-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_project_equipment_unique_together_and_more'),
    ]

    operations = [
        # 为 Project_Equipment 添加复合主键
        migrations.RemoveField(
            model_name='project_equipment',
            name='id',
        ),
        migrations.AddField(
            model_name='project_equipment',
            name='pk',
            field=models.CompositePrimaryKey('project_id', 'equipment_id', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        # 为 Project_Equipment_Schedule 添加复合主键
        migrations.RemoveField(
            model_name='project_equipment_schedule',
            name='id',
        ),
        migrations.AddField(
            model_name='project_equipment_schedule',
            name='pk',
            field=models.CompositePrimaryKey('project_id', 'equipment_id', 'phase', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        # 为 Project_Equipment_Schedule_History 添加复合主键
        migrations.RemoveField(
            model_name='project_equipment_schedule_history',
            name='id',
        ),
        migrations.AddField(
            model_name='project_equipment_schedule_history',
            name='pk',
            field=models.CompositePrimaryKey('project_id', 'equipment_id', 'phase', 'modified_at', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        # 为 ProjectEquipmentComponent 添加复合主键
        migrations.RemoveField(
            model_name='projectequipmentcomponent',
            name='id',
        ),
        migrations.AddField(
            model_name='projectequipmentcomponent',
            name='pk',
            field=models.CompositePrimaryKey('project_id', 'equipment_id', 'component_id', blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
