# Generated by Django 6.0 on 2025-12-23 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_fix_project_equipment_constraints'),
    ]

    operations = [
        # 为 Project_Equipment 添加复合主键约束
        migrations.RunSQL(
            "ALTER TABLE common_project_equipment ADD PRIMARY KEY (project_id, equipment_id);",
            reverse_sql="ALTER TABLE common_project_equipment DROP PRIMARY KEY;"
        ),
        # 为 Project_Equipment_Schedule 添加复合主键约束
        migrations.RunSQL(
            "ALTER TABLE common_project_equipment_schedule ADD PRIMARY KEY (project_id, equipment_id, phase);",
            reverse_sql="ALTER TABLE common_project_equipment_schedule DROP PRIMARY KEY;"
        ),
        # 为 Project_Equipment_Schedule_History 添加复合主键约束
        migrations.RunSQL(
            "ALTER TABLE common_project_equipment_schedule_history ADD PRIMARY KEY (project_id, equipment_id, phase, modified_at);",
            reverse_sql="ALTER TABLE common_project_equipment_schedule_history DROP PRIMARY KEY;"
        ),
        # 为 ProjectEquipmentComponent 添加复合主键约束
        migrations.RunSQL(
            "ALTER TABLE common_project_equipment_component ADD PRIMARY KEY (project_id, equipment_id, component_id);",
            reverse_sql="ALTER TABLE common_project_equipment_component DROP PRIMARY KEY;"
        ),
    ]
