# Generated by Django 6.0 on 2025-12-23 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_add_composite_primary_keys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComponentInfo',
            new_name='Component_Info',
        ),
        migrations.RenameModel(
            old_name='ProjectEquipmentComponent',
            new_name='Project_Equipment_Component',
        ),
    ]
