# Generated by Django 6.0 on 2025-12-23 04:48

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('common', '0007_rename_componentinfo_component_info_and_more'),
    ]
    operations = [
    ]
