# Generated by Django 6.0 on 2026-01-19 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_project_equipment_unique_together_and_more'),
    ]

    operations = [
    ]
