# Generated by Django 6.0 on 2026-01-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_project_equipment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project_equipment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='project_equipment_component',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='project_equipment_schedule',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='project_equipment_schedule_history',
            unique_together=set(),
        ),
    ]
